language: python
python:
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
script:
  - python manage.py test airline_manager
  - coverage run --source=airline_manager manage.py test airline_manager
after_success:
  - coveralls